// <auto-generated />
using HMSS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMSS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMSS.Models.Departement", b =>
                {
                    b.Property<int>("id_Dep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Dep"));

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.HasKey("id_Dep");

                    b.ToTable("Departements", "HMSS");
                });

            modelBuilder.Entity("HMSS.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("Department_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("speciality")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.HasKey("DoctorId");

                    b.HasIndex("Department_id");

                    b.ToTable("Doctors", "HMSS");
                });

            modelBuilder.Entity("HMSS.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<int>("Doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPatient");

                    b.HasIndex("Doctor_id");

                    b.ToTable("Patients", "HMSS");
                });

            modelBuilder.Entity("HMSS.Models.Doctor", b =>
                {
                    b.HasOne("HMSS.Models.Departement", "departement")
                        .WithMany("doctors")
                        .HasForeignKey("Department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departement");
                });

            modelBuilder.Entity("HMSS.Models.Patient", b =>
                {
                    b.HasOne("HMSS.Models.Doctor", "doctor")
                        .WithMany("patients")
                        .HasForeignKey("Doctor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("HMSS.Models.Departement", b =>
                {
                    b.Navigation("doctors");
                });

            modelBuilder.Entity("HMSS.Models.Doctor", b =>
                {
                    b.Navigation("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
